name: fancy_factory
description: A factory for flutter widgets on fancy way.
homepage: https://github.com/rcorbellini/FancyFactory

version: 0.5.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fancy_stream: ^3.0.0
  chameleon_resolver: ^0.0.1
  flutter_tags: ^1.0.0-nullsafety.1


dev_dependencies:
  test: ^1.3.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true